# render.yaml (stavi u korijen repozitorijuma)
services:
  - type: web
    name: rezervacije-klijent
    env: static
    buildCommand: cd rezervacije/klijent && yarn install && yarn build
    staticPublishPath: rezervacije/klijent/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        