# render.yaml (stavi u korijen repozitorijuma)
services:
  - type: web
    name: rezervacije-klijent
    env: static
    rootDir: klijent
    buildCommand: yarn install && yarn build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        